version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest saaruhaasan.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push saaruhaasan.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
artifacts:
  files:
    - deployment.yaml
    - service.yaml

